django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("workout.urls"))
]

workout/urls.py
from django.urls import path
from .views import MesocycleListView, WeekListView

urlpatterns = [
    path("mesocycle/<int:pk>", WeekListView.as_view(), name="week"),
    path("", MesocycleListView.as_view(), name="mesocycle"),
]

workout/models.py
from django.db import models
from django.urls import reverse


class Mesocycle(models.Model):
    mesocycle = models.CharField(default=1, max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.mesocycle


class Week(models.Model):
    week = models.CharField(default=1, max_length=200)
    mesocycle = models.ForeignKey(Mesocycle, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.week


class Day(models.Model):
    day = models.CharField(default=1,max_length=200)
    week = models.ForeignKey(Week, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.day


class Exercise(models.Model):
    exercise = models.CharField(max_length=200)
    focus = models.CharField(max_length=200)
    url = models.URLField(max_length=300)
    tenRepMax = models.IntegerField()
    type = models.CharField(max_length=200)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.exercise


class Workout(models.Model):
    exercise = models.ForeignKey(Exercise, on_delete=models.RESTRICT)
    setCount = models.IntegerField()
    weight = models.IntegerField()
    repGoal = models.IntegerField()
    repResult = models.IntegerField()
    sorenessRating = models.IntegerField()
    pumpRating = models.IntegerField()
    day = models.ForeignKey(Day, on_delete=models.CASCADE)
    creator = models.ForeignKey(
        "auth.User",
        on_delete=models.CASCADE,
    )
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.exercise.exercise

    def get_absolute_url(self):
        return reverse("workout_detail", kwargs={"pk": self.pk})

workout/views.py
from django.views.generic import ListView
from .models import *


class MesocycleListView(ListView):
    model = Mesocycle
    template_name = "mesocycle.html"


class WeekListView(ListView):
    model = Week
    weeks = Week.objects.select_related().all()
    template_name = "week.html"


class DayListView(ListView):
    model = Day
    template_name = "day.html"

workout/templates/base.html
{% load static %}
<html>
    <head>
        <title>Workout</title>
        <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>

    <body>
        <header>
            <h1>
                <a href="{% url 'mesocycle' %}">Home</a>
            </h1>
        </header>
        <div>
            {% block content %}
            {% endblock content %}
        </div>
    </body>
</html>

workout/templates/mesocycle.html
{% extends "base.html" %}

{% block content %}
{% for mesocycle in mesocycle_list %}
    <div class="mesocycle">
        <h2>
            <a href="">{{ mesocycle.mesocycle }}</a>
        </h2>
    </div>
{% endfor %}
{% endblock content %}

workout/templates/week.html
{% extends "base.html" %}

{% block content %}
{% for w in weeks %}
    <div class="week">
        <h2>
            <a href="">{{w.week}}</a>
        </h2>
    </div>
{% endfor %}
{% endblock content %}